1. Write a Python function called add_numbers that takes two numbers as arguments and returns their sum. Then, test the function by calling it with two numbers of your choice.

In [4]:
def add_number(num1, num2):
  return num1+num2

add_number(2,3)

5

2. Create a Python function called currency_converter() that takes two arguments:

- amount: The amount of money to be converted (in USD).
- exchange_rate (default is 280): The conversion rate from USD to another currency (e.g., PKR). You can assume the default rate is 1 USD = 280 PKR.

The function should return a message showing how much the given amount is worth in the target currency (PKR).

In [5]:
def currency_converter(a,exchange_rate=280):
  return a*exchange_rate

currency_converter(4)

1120

3. Write a Python function display_student_info that accepts the following details about a student:

- name (Keyword argument): The name of the student.
- age (Keyword argument): The age of the student.
- grade (Keyword argument): The grade the student is in.
- school (Keyword argument): The name of the school the student attends.

In [16]:
def display_student_info(**info):
  return info
display_student_info(name='Iqra', age='22', grade='A', school='ZABIST')

{'name': 'Iqra', 'age': '22', 'grade': 'A', 'school': 'ZABIST'}

4. Write a Python function calculate_price that accepts two positional arguments:
price: The price of a single item.
quantity: The number of items bought.
The function should return the total price by multiplying price and quantity.

In [46]:
def calculate_price(price, quantity):
    return price * quantity
total = calculate_price(50, 3)
print(f"Total Price: ${total}")

Total Price: $150

5. Write a Python function display_prices that takes a product name and an arbitrary number of keyword arguments representing product prices. The function should display each product and its price.

Product: Laptop

Amazon: $800

eBay: $750

Walmart: $780

In [30]:
def display_prices(name, **prices):
  print(f"product: {name}")
  for product_source, prices in prices.items():
    print(f"{product_source}: ${prices}")
display_prices('laptop', Amazon= '$800', eBay='$750', Walmart='$780')

product: laptop
Amazon: $$800
eBay: $$750
Walmart: $$780

6. Write a Python function find_max that takes any number of numerical arguments and returns the maximum number.

In [34]:
def find_max(*num):
  return max(num)
find_max(3,4,5,7,4,355,3657,5)

3657

7. Write a Python function display_info that takes:
Positional arguments for the name and age of a person.
Keyword arguments for other personal details like address, phone number, and email.
Example Output:

- Name: Alice
- Age: 30
- Other Details:
    - address: 123 Main St
    - phone: 123-456-7890
    - email: alice@example.com

In [44]:
def display_info(name, age, **other_details):
  print(f"Name: {name}")
  print(f"Age: {age}")
  print("Other Details:")
  for key, value in other_details.items():
    print(f"  .  {key}: {value}")
display_info('Alice', 30, address='123 Main St', phone='123-345-7890', email='example@gmail.com')

Name: Alice
Age: 30
Other Details:
  .  address: 123 Main St
  .  phone: 123-345-7890
  .  email: example@gmail.com

8. products = [ {"name": "Laptop", "price": 1200, "in_stock": True, "discount": 0.1}, {"name": "Smartphone", "price": 800, "in_stock": False, "discount": 0.05}, {"name": "Headphones", "price": 150, "in_stock": True, "discount": 0.2}, {"name": "Smartwatch", "price": 300, "in_stock": True, "discount": 0}, {"name": "Keyboard", "price": 100, "in_stock": True, "discount": 0.15} ]

- Get names of in-stock products:

*Use list comprehension to generate a list of names for the products that are in stock.

- Calculate final prices for in-stock products after discount:

*For products that have a discount, calculate the final price by applying the discount.

*For products with no discount, keep the original price.

- Generate a list of tuples with the product name and its final price.

Example Output:

- In-stock product names: ['Laptop', 'Headphones', 'Smartwatch', 'Keyboard']
- Discounted prices: [('Laptop', 1080.0), ('Headphones', 120.0), ('Smartwatch', 300), ('Keyboard', 85.0)]

In [45]:
products = [
    {"name": "Laptop", "price": 1200, "in_stock": True, "discount": 0.1},
    {"name": "Smartphone", "price": 800, "in_stock": False, "discount": 0.05},
    {"name": "Headphones", "price": 150, "in_stock": True, "discount": 0.2},
    {"name": "Smartwatch", "price": 300, "in_stock": True, "discount": 0},
    {"name": "Keyboard", "price": 100, "in_stock": True, "discount": 0.15}
]

# Get names of in-stock products
in_stock_names = [product["name"] for product in products if product["in_stock"]]

# Calculate final prices after discount
discounted_prices = [
    (product["name"], product["price"] * (1 - product["discount"]))
    for product in products if product["in_stock"]
]

# Output
print("In-stock product names:", in_stock_names)
print("Discounted prices:", discounted_prices)

In-stock product names: ['Laptop', 'Headphones', 'Smartwatch', 'Keyboard']
Discounted prices: [('Laptop', 1080.0), ('Headphones', 120.0), ('Smartwatch', 300), ('Keyboard', 85.0)]

9.Create a list of even numbers between 1 and 20. (List Comprehension)

In [37]:
numbers_1_20 = [num for num in range(1,21)]
evens = [num for num in numbers_1_20 if num%2==0]
evens

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

10. Create a list of numbers, generate a new list containing only the numbers that are divisible by 3 or 5. (List Comprehension)

In [35]:
numbers = [2,3,5,6,7,8,9,4,16,8,67,8,43,12,45,22,45,67,89,90,23,33,43,56,45,567]
devisible_numbers = []
for num in numbers:
  if num%3==0 or num%5==0:
    devisible_numbers.append(num)
print(devisible_numbers)

[3, 5, 6, 9, 12, 45, 45, 90, 33, 45, 567]

In [36]:
numbers = [2,3,5,6,7,8,9,4,16,8,67,8,43,12,45,22,45,67,89,90,23,33,43,56,45,567]
devisible_numbers =[num for num in numbers if num%3==0 or num%5==0]
print(devisible_numbers)

[3, 5, 6, 9, 12, 45, 45, 90, 33, 45, 567]